### ISSUE TITLE
start workout screen

### ISSUE THREAD

**Issue by mariniem** [mariniem/trayn#39]
## Value statement 
As a User
I need a screen
so that I can start my created workout

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/56030872/70810212-a1498680-1dc3-11ea-908a-500aa52e6833.png)

- pictures of choosen exercises with skip function
- timer function 

## Acceptance criteria
- [ ] picture of first choosen exercise
- [ ] option to skip exercise
- [ ] start timer and then spring to next exercise
- [ ] possibility to pause

## Tasks
- [ ] add component Timer and StartWorkout
- [ ] test mobile and in desktop view

## Size
L
