### ISSUE TITLE
info with short description on start screen

### ISSUE THREAD

**Issue by mariniem** [mariniem/trayn#40]
## Value statement 
As a User
I need an info filed
so that I can read the description of this exercise before starting the exercise 

## Description (Text, Scribble, Wireframe, Design)
- info icon on exercise picture

## Acceptance criteria
- [ ] info icon
- [ ] on click it shows a short description of this exercise 

## Tasks
- [ ] add a info component 
- [ ] on click description is shown
- [ ] test in mobile and desktop

## Size
S
